id: P1545B659
initial_creation_type: input
source_metadata:
  Title: Mañjuvajramukhyākhyāna
  Editor: Kimiaki Tanaka
  Publisher: Watanabeshuppan
  Place of Publication: Tokyo, Japan
  Year: '2018'
  Mañjuvajramukhyākhyāna:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: '2019'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:21:01.480751'
last_modified_at: '2022-03-08T17:21:01.480760'
